language: C

git:
  quiet: true
  submodules: false

matrix:
  include:
    - os: linux
      dist: bionic

compiler: gcc

before_install: 
  - wget https://github.com/libcheck/check/releases/download/0.13.0/check-0.13.0.tar.gz
  - tar xvf check-0.13.0.tar.gz
  - cd check-0.13.0
  - ./configure
  - make
  - sudo make install
  - git clone https://github.com/AaronV77/Thread_Safe_Queue.git
  - make
  - cd tests
  - make

script:
  - bash test.sh
  - ./c || travis_terminate 1;
